# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/daniilnedaiborsch/Code/CppClinter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/daniilnedaiborsch/Code/CppClinter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daniilnedaiborsch/Code/CppClinter/CMakeFiles /Users/daniilnedaiborsch/Code/CppClinter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daniilnedaiborsch/Code/CppClinter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CppClinter

# Build rule for target.
CppClinter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CppClinter
.PHONY : CppClinter

# fast build rule for target.
CppClinter/fast:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/build
.PHONY : CppClinter/fast

src/CAlphabet.o: src/CAlphabet.cpp.o

.PHONY : src/CAlphabet.o

# target to build an object file
src/CAlphabet.cpp.o:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/CAlphabet.cpp.o
.PHONY : src/CAlphabet.cpp.o

src/CAlphabet.i: src/CAlphabet.cpp.i

.PHONY : src/CAlphabet.i

# target to preprocess a source file
src/CAlphabet.cpp.i:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/CAlphabet.cpp.i
.PHONY : src/CAlphabet.cpp.i

src/CAlphabet.s: src/CAlphabet.cpp.s

.PHONY : src/CAlphabet.s

# target to generate assembly for a file
src/CAlphabet.cpp.s:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/CAlphabet.cpp.s
.PHONY : src/CAlphabet.cpp.s

src/Lexeme.o: src/Lexeme.cpp.o

.PHONY : src/Lexeme.o

# target to build an object file
src/Lexeme.cpp.o:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/Lexeme.cpp.o
.PHONY : src/Lexeme.cpp.o

src/Lexeme.i: src/Lexeme.cpp.i

.PHONY : src/Lexeme.i

# target to preprocess a source file
src/Lexeme.cpp.i:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/Lexeme.cpp.i
.PHONY : src/Lexeme.cpp.i

src/Lexeme.s: src/Lexeme.cpp.s

.PHONY : src/Lexeme.s

# target to generate assembly for a file
src/Lexeme.cpp.s:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/Lexeme.cpp.s
.PHONY : src/Lexeme.cpp.s

src/LexemeType.o: src/LexemeType.cpp.o

.PHONY : src/LexemeType.o

# target to build an object file
src/LexemeType.cpp.o:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/LexemeType.cpp.o
.PHONY : src/LexemeType.cpp.o

src/LexemeType.i: src/LexemeType.cpp.i

.PHONY : src/LexemeType.i

# target to preprocess a source file
src/LexemeType.cpp.i:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/LexemeType.cpp.i
.PHONY : src/LexemeType.cpp.i

src/LexemeType.s: src/LexemeType.cpp.s

.PHONY : src/LexemeType.s

# target to generate assembly for a file
src/LexemeType.cpp.s:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/LexemeType.cpp.s
.PHONY : src/LexemeType.cpp.s

src/Lexer.o: src/Lexer.cpp.o

.PHONY : src/Lexer.o

# target to build an object file
src/Lexer.cpp.o:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/Lexer.cpp.o
.PHONY : src/Lexer.cpp.o

src/Lexer.i: src/Lexer.cpp.i

.PHONY : src/Lexer.i

# target to preprocess a source file
src/Lexer.cpp.i:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/Lexer.cpp.i
.PHONY : src/Lexer.cpp.i

src/Lexer.s: src/Lexer.cpp.s

.PHONY : src/Lexer.s

# target to generate assembly for a file
src/Lexer.cpp.s:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/Lexer.cpp.s
.PHONY : src/Lexer.cpp.s

src/SString.o: src/SString.cpp.o

.PHONY : src/SString.o

# target to build an object file
src/SString.cpp.o:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/SString.cpp.o
.PHONY : src/SString.cpp.o

src/SString.i: src/SString.cpp.i

.PHONY : src/SString.i

# target to preprocess a source file
src/SString.cpp.i:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/SString.cpp.i
.PHONY : src/SString.cpp.i

src/SString.s: src/SString.cpp.s

.PHONY : src/SString.s

# target to generate assembly for a file
src/SString.cpp.s:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/SString.cpp.s
.PHONY : src/SString.cpp.s

src/finders.o: src/finders.cpp.o

.PHONY : src/finders.o

# target to build an object file
src/finders.cpp.o:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/finders.cpp.o
.PHONY : src/finders.cpp.o

src/finders.i: src/finders.cpp.i

.PHONY : src/finders.i

# target to preprocess a source file
src/finders.cpp.i:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/finders.cpp.i
.PHONY : src/finders.cpp.i

src/finders.s: src/finders.cpp.s

.PHONY : src/finders.s

# target to generate assembly for a file
src/finders.cpp.s:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/finders.cpp.s
.PHONY : src/finders.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CppClinter.dir/build.make CMakeFiles/CppClinter.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CppClinter"
	@echo "... src/CAlphabet.o"
	@echo "... src/CAlphabet.i"
	@echo "... src/CAlphabet.s"
	@echo "... src/Lexeme.o"
	@echo "... src/Lexeme.i"
	@echo "... src/Lexeme.s"
	@echo "... src/LexemeType.o"
	@echo "... src/LexemeType.i"
	@echo "... src/LexemeType.s"
	@echo "... src/Lexer.o"
	@echo "... src/Lexer.i"
	@echo "... src/Lexer.s"
	@echo "... src/SString.o"
	@echo "... src/SString.i"
	@echo "... src/SString.s"
	@echo "... src/finders.o"
	@echo "... src/finders.i"
	@echo "... src/finders.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

